---
- name: installation tasks (sudo access required)
  hosts: workstations
  tasks:
  - name: install dev tools
    action: yum name=$item state=latest
    with_items:
      - vim-enhanced
      - ranger
      - tmux
      - htop
      - iotop
      - iftop
      - nload
      - mtr
      - zsh
      - make
      - cmake
      - automake
      - gcc
      - gcc-c++
      - clang-devel
      - python-devel
      - git
      - tig
      - ack
      - mercurial
      - ack
      - protobuf-compiler
      - python-virtualenv
      - python-virtualenvwrapper
      - zeromq-devel
      - readline-devel
      - openssl-devel
      - R
      # needed for numpy/scipy/lxml
      - blas-devel
      - lapack-devel
      - atlas
      - libxslt-devel
      - libxml2-devel
    tags:
      - packages

  - name: install user stuff
    action: yum name=$item state=latest
    with_items:
      - levien-inconsolata-fonts
      - terminus-fonts
      - terminus-fonts-console
      - mosh
      - sshfs
      - stow
      - stow-doc
      - transmission-daemon
      - transmission-cli
      - pv
    tags:
      - packages
  - name: imgur CLI
    shell: creates=/usr/local/bin/imgur curl http://imgur.com/tools/imgurbash.sh > /usr/local/bin/imgur ; chmod a+x /usr/local/bin/imgur

  - name: Determining username
    action: shell whoami
    register: whoami
    sudo: False

  - name: Changing the default shell to zsh
    action: user shell=/bin/zsh user=${whoami.stdout}

- name: gui workstation installation tasks (sudo access required)
  hosts: gui-workstations
  tasks:
  - name: install gui tools
    yum: name=$item state=latest
    with_items:
      - cmus
      - gnome-tweak-tool
    tags:
      - packages
      - gui

  - name: install nonfree programs and tools
    shell: yum -y --nogpgcheck localinstall $item
    with_items:
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm # Google Chrome
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-19.noarch.rpm # rpmfusion
      - https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-1.6.0-1.fedora.x86_64.rpm # dropbox
      - http://download.virtualbox.org/virtualbox/4.2.16/VirtualBox-4.2-4.2.16_86992_fedora18-1.x86_64.rpm # VBox
      - http://files.vagrantup.com/packages/95d308caaecd139b8f62e41e7add0ec3f8ae3bd1/vagrant_1.2.3_x86_64.rpm # Vagrant
    tags:
      - packages
      - gui

### NON ROOT TASKS

- name: Entering Plugin Nirvana
  hosts: workstations
  sudo: False
  tags:
    - dotfiles

  tasks:
  - name: clone dotfiles
    shell: creates=~/.dotfiles git clone --recursive git@github.com:ryansb/dotfiles ~/.dotfiles
    # TODO: when git module supports --recursive, change to that
    # git: repo=ssh://git@github.com/ryansb/dotfiles.git dest=~/.dotfiles

  - name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
    shell: creates=~/.spf13-vim-3 chdir=~/ curl http://j.mp/spf13-vim3 -L -o - | sh

  - file: src=~/.dotfiles/zsh/.zshrc dest=~/.zshrc state=link
  - file: src=~/.dotfiles/zsh/.zlogin dest=~/.zlogin state=link
  - file: src=~/.dotfiles/zsh/custom dest=~/.dotfiles/zsh/.zprezto/modules/custom  state=link
  - file: src=~/.dotfiles/zsh/prompt dest=~/.dotfiles/zsh/.zprezto/modules/prompt/functions/prompt_ryansb_setup state=link
  - file: src=~/.dotfiles/zsh/.zprezto/runcoms/zlogout dest=~/.dotfiles/zsh/.zlogout state=link
  - file: src=~/.dotfiles/zsh/.zprezto/runcoms/zprofile dest=~/.dotfiles/zsh/.zprofile state=link

  - name: making misc symlinks
    file: src=~/.dotfiles/$item dest=~/.$item state=link
    with_items:
      - tmux
      - gitconfig
      - hgrc
      - screenrc
      - tmux.conf
      - vimrc.bundles.local
      - vimrc.local
      - Rprofile
      - Renviron

- name: Install development languages from source
  hosts: workstations
  sudo: False
  tags:
    - source

  tasks:
  - name: cloning golang
    shell: creates=~/.golang hg clone -u release https://code.google.com/p/go ~/.golang

  - name: compiling golang
    shell: creates=~/.golang chdir=~/.golang/src ~/.golang/src/make.bash

  - name: installing rvm
    shell: creates=~/.rvm chdir=~/ curl -L https://get.rvm.io | bash -s stable --ruby

  - name: making R module dir
    file: path=~/.rlang/lib/ state=directory

- name: Install misc servers
  hosts: devservers
  tags:
    - servers

  tasks:
  - name: grabbing libssl.so.6 for dependencies
    yum: name=$item state=latest
    with_items:
      - ftp://ftp.pbone.net/mirror/ftp.scientificlinux.org/linux/scientific/6.0/x86_64/os/Packages/openssl098e-0.9.8e-17.el6.x86_64.rpm # for libssl.so.6 cleanup when possible
      - http://packages.couchbase.com/releases/2.0.1/couchbase-server-community_x86_64_2.0.1.rpm
