---
- name: installation tasks (sudo access required)
  hosts: workstations
  tasks:
  - name: install dev tools
    action: yum name=$item state=latest
    with_items:
      - vim-enhanced
      - ranger
      - tmux
      - htop
      - iotop
      - mtr
      - zsh
      - make
      - cmake
      - automake
      - gcc
      - gcc-c++
      - clang-devel
      - python-devel
      - readline-devel
      - git
      - ack
      - mercurial
      - python-virtualenv
      - python-virtualenvwrapper
      - zeromq-devel
      - R
      # needed for numpy/scipy/lxml
      - blas-devel
      - lapack-devel
      - atlas
      - libxslt-devel
      - libxml2-devel
    tags:
      - packages

  - name: install user stuff
    action: yum name=$item state=latest
    with_items:
      - levien-inconsolata-fonts
      - mosh
      - sshfs
      - transmission-daemon
      - transmission-cli
      #- gnome-tweak-tool
    tags:
      - packages

  - name: Determining username
    action: shell whoami
    register: whoami
    sudo: False

  - name: Changing the default shell to zsh
    action: user shell=/bin/zsh user=${whoami.stdout}

### NON ROOT TASKS

- name: Entering Plugin Nirvana
  hosts: workstations
  sudo: False
  tags:
    - dotfiles

  tasks:
  - name: clone dotfiles
    shell: creates=~/.dotfiles git clone --recursive git@github.com:ryansb/dotfiles ~/.dotfiles
    # TODO: when git module supports --recursive, change to that
    # git: repo=ssh://git@github.com/ryansb/dotfiles.git dest=~/.dotfiles

  - name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
    shell: creates=~/.spf13-vim-3 curl http://j.mp/spf13-vim3 -L -o - | sh

  - file: src=~/.dotfiles/zsh/.zshrc dest=~/.zshrc state=link
  - file: src=~/.dotfiles/zsh/.zlogin dest=~/.zlogin state=link
  - file: src=~/.dotfiles/zsh/custom dest=~/.dotfiles/zsh/.zprezto/modules/custom  state=link
  - file: src=~/.dotfiles/zsh/prompt dest=~/.dotfiles/zsh/.zprezto/modules/prompt/functions/prompt_ryansb_setup state=link
  - file: src=~/.dotfiles/zsh/.zprezto/runcoms/zlogout dest=~/.dotfiles/zsh/.zlogout state=link
  - file: src=~/.dotfiles/zsh/.zprezto/runcoms/zprofile dest=~/.dotfiles/zsh/.zprofile state=link

  - name: making misc symlinks
    file: src=~/.dotfiles/$item dest=~/.$item state=link
    with_items:
      - tmux
      - gitconfig
      - hgrc
      - screenrc
      - tmux.conf
      - vimrc.bundles.local
      - vimrc.local
      - Rprofile
      - Renviron

- name: Install local golang
  hosts: workstations
  sudo: False
  tags:
    - source

  tasks:
  - name: cloning golang
    shell: creates=~/.golang hg clone -u release https://code.google.com/p/go ~/.golang

  - name: compiling golang
    shell: chdir=~/.golang/src ~/.golang/src/all.bash

  - name: installing rvm
    shell: creates=~/.rvm curl -L https://get.rvm.io | bash -s stable --ruby

  - name: making R module dir
    file: dest=~/.rlang/lib/
